### ISSUE TITLE
[Stargate] install problems [pastebin download problem]

### ISSUE THREAD

**Issue by Nex4rius** [Nex4rius/Stargate-Programm#267]
>@craig1988 https://github.com/Nex4rius/Nex4rius-Programme/commit/e2d311ec78ee8649ebdb67aaa83e5bbdf51303cc#commitcomment-21516441
Hey look sorry to be a pain in the ass but I'm try to install his on open computer had it working then my world crashed now ever time I install it I get attempt to index nil value error. I'm not very literate in computer code so would appacaite the help as I loved the program
Please can you help me out mate thanks

Do you have OpenOS 1.5 or OpenOS 1.6?
Have you tried to install it on a fresh installation of OpenOS or on the same computer that had it installed before?
My best guess at the moment is that you tried to change a setting or an address and made a mistake which results that my programm gets an error when reading the files.
(Right now my program doesn't check if those two files contain valid code before running them)

Could you move your addresses and delete the rest by typing this in the computer:
>move /stargate/adressen.lua /adressen.lua
del /stargate -r

and then try to install it again?

**Comment by craig1988** [comment]
Yeh tried all that doesn't seem to be working humm I'm running 1.6.1

**Comment by craig1988** [comment]
Is there anyway I can send you a picture of the error

**Comment by Nex4rius** [comment]
Just upload a screenshot somewhere for example http://imgur.com/

**Comment by craig1988** [comment]
It's fresh installation

**Comment by craig1988** [comment]
Cool how do I find u on that app

**Comment by Nex4rius** [comment]
Just send a link

**Comment by craig1988** [comment]
My name on Miguel is craigjohnstonadad365

**Comment by craig1988** [comment]
Imgur *

**Comment by craig1988** [comment]
https://imgur.com/user/craigjohnstonadad365


Sent from my iPhone

**Comment by craig1988** [comment]
Sorry there's the link

**Comment by craig1988** [comment]
Thanks for trying to help me out mate it's really bothering me as it was working so well before

**Comment by craig1988** [comment]
It's the error at the top of the page obvs

**Comment by Nex4rius** [comment]
<img src="https://i.imgur.com/Z9IhW7r.jpg" width="700px"/>

**Comment by craig1988** [comment]
Yes the one at the top after it say running

**Comment by craig1988** [comment]
The other code further down is obvs the fixes you suggested I'm sure it something really simple I just don't have the know how

**Comment by Nex4rius** [comment]
Hm I have OpenOS 1.6 not 1.6.1
I'm gonna update my opencomputers.

**Comment by craig1988** [comment]
Cool I really wanna fix this issue it's killing me lol

**Comment by craig1988** [comment]
This it without all the other junk
https://imgur.com/a/idTLh
via Imgur for iOS


Sent from my iPhone

**Comment by craig1988** [comment]
This comes up aswell sometimes https://i.imgur.com/cwHBkAa.jpg
via Imgur for iOS


Sent from my iPhone

**Comment by Nex4rius** [comment]
This is strange. It gets the error because the file downloaded from pastebin is empty.
I've tried now to download other files from pastebin and they are all empty.

**Comment by craig1988** [comment]
Hummm you think it a problem with pastebin itself

**Comment by Nex4rius** [comment]
Yes something is bugged with pastebin but there are other methods to download the program.

Write this instead:
>wget -f https://raw.githubusercontent.com/Nex4rius/Nex4rius-Programme/master/Stargate-Programm/installieren.lua /installieren.lua


and then this
>/installieren.lua


The updater works without pastebin so there shouldnt be any problems later.

**Comment by craig1988** [comment]
Your a complete boss mate it's working perfectly

**Comment by craig1988** [comment]
Thank you so much

**Comment by craig1988** [comment]
Have you made any other program out of curiously

**Comment by Nex4rius** [comment]
Yes I've made other programs. For example my tank display program <a href="https://github.com/Nex4rius/Nex4rius-Programme/tree/master/Tank">here</a>.
