### ISSUE TITLE
[Stargate] Issues 

### ISSUE THREAD

**Issue by craig1988** [Nex4rius/Stargate-Programm#272]
Sorry my bad

**Comment by craig1988** [comment]
I'll comment here from now on I was asked to update on the start up and now my whole program has gone down

**Comment by craig1988** [comment]
Now it just keeps kicking me out to the open is screen

**Comment by Nex4rius** [comment]
On startup it will show you your current version, the master version on github and the beta version on github.
When there is a new beta version it will ask you in the opening screen but you don't have update.

You should try to launch it with
<code>stargate ja</code>

**Comment by craig1988** [comment]
On start up it starts up as normal and then flicks to a smaller screen in the Conner and then throws me back to the openos home screen

**Comment by Nex4rius** [comment]
yes in openos home screen write
<code>stargate ja</code>

**Comment by craig1988** [comment]
I think I updated by mistake is there anyway I would be able to down grade again

**Comment by Nex4rius** [comment]
write
<code>stargate ja</code>

If that doesn't work you will have to reinstall it completly because in the beta version I've changed something in the updater and if thats broken...

**Comment by craig1988** [comment]
Ok that no problem I'm sorry for all the comments. How do I go about reinstalling it

**Comment by craig1988** [comment]
Yeh when I type that it says I have beta version

**Comment by craig1988** [comment]
Can't find the text that you send me yesterday sorry

**Comment by craig1988** [comment]
I operate about 20 stargate a in my world so that's why I'm in such a pickle to get it working

**Comment by Nex4rius** [comment]
ok type in these commands one line at a time
<hr>
<code>del stargate -r</code>
<hr>
<code>wget -f https://raw.githubusercontent.com/Nex4rius/Nex4rius-Programme/master/Stargate-Programm/installieren.lua /installieren.lua</code>
<hr>
<code>/installieren.lua</code>
<hr>

<a href="https://github.com/Nex4rius/Nex4rius-Programme/blob/beta/Stargate-Programm/README.md#english">btw I think this should explain everything for the future</a>

**Comment by Nex4rius** [comment]
ops wait

**Comment by craig1988** [comment]
Is wget ("-f" followed by the http or separate

**Comment by Nex4rius** [comment]
oh ok I've edited it now. Try again :)

**Comment by craig1988** [comment]
Right all working again mate installed manually on all 20 start gates lol thanks so much for all your help

**Comment by craig1988** [comment]
I have a goauld style world with about 50 planets from advanced Rocketry many of them with villages with startagtes installed so it's essential that your program can save failing addressss

**Comment by craig1988** [comment]
Really appreciate all the work you out in on the program my got about 7 or at goauld mother ships in orbit aswell with stargate aboard so thanks so much again

**Comment by Nex4rius** [comment]
Good to hear that it works again :)
