### ISSUE TITLE
[Tank] Not working with "Pressure Pipes".

### ISSUE THREAD

**Issue by IgorZerato** [Nex4rius/Stargate-Programm#277]
Hello, first of all, thank you for making such a cool program.
But nothing is shown on the server when clients are plugged into a "Pressure Pipes" tank, is there any way to make it work? Thank you!

**Comment by Nex4rius** [comment]
I don't know anything about the mod pressure pipes :(
Are you sure that the tank is a "real" fluid container like all the other mods? Because if the OpenComputer Tank Controller cannot detect it then I cannot do anything.

**Comment by Nex4rius** [comment]
I just tested it and it looks like a very easy "fix". You just have to place the adapter next to a tank access port :)

**Comment by IgorZerato** [comment]
LOL
The access door was not documented, but it worked very well, thanks for the quick response and the excellent program!
