### ISSUE TITLE
[Stargate] Problem with download

### ISSUE THREAD

**Issue by RA3236** [Nex4rius/Stargate-Programm#309]
When I attempt pastebin run -f YVqKFnsP, the following occurs (i tried a LOT of times):
![2017-06-28_14 12 26](https://user-images.githubusercontent.com/18625897/27620289-01d99be2-5c0c-11e7-8412-ea526e8ebf2a.png)

**Comment by Nex4rius** [comment]
You forgot a step in the installation. The OpenOS floppy disk is read only. You have to install OpenOS to a hard drive before you can save any new file.
Just insert a hard disk and write "install" and then select the drive you want to install to.

I have a video were I showed the **entire** process to get the program running <a href="https://www.youtube.com/embed/MgWY4es5oEs">here</a>
