### ISSUE TITLE
Issue with Iris Deactivation Code [MC 1.10.2]

### ISSUE THREAD

**Issue by craft90** [Nex4rius/Stargate-Programm#357]
So I'm having a bit of a pickle with this. For some reason when I try to enter the IDC nothing appears to happen. Both gates are chunk loaded and both have Wi-Fi cards in the computers. But when I try to remotely open the gate via the GUI it chews away with Sending IDC until the time limit goes up and the Stargate closes.  Meanwhile the Minecraft log whines about the sever being the sever being overloaded despise me giving it 6 GB of RAM to work with. I don't know what I'm doing wrong.

**Comment by craft90** [comment]
Did some more testing. I wasn't inputting the correct code. Whoops. Works now.

**Comment by Nex4rius** [comment]
lol
