### ISSUE TITLE
Server side does not work

### ISSUE THREAD

**Issue by notchriss** [Nex4rius/Stargate-Programm#362]
When I run "tank" or when it runs on startup, all I get is a screen flashing different colors for a couple of seconds, then there's a German message for "waiting for data" and a second later I'm back to command line /home # or whichever directory I was before. 

The client/tank part seems to work fine, it does display the data and also broadcasts it every few seconds. If I run lua console event.pull("modem") I do receive the data about tank (screenshot) so the connection between computers must be fine.  

![2017-11-07_18 18 21](https://user-images.githubusercontent.com/8706925/32504284-182c1df4-c3e8-11e7-9a91-89bd15cf7487.png)

Minecraft 1.7.10

**Comment by Nex4rius** [comment]
If you run tank manually are there any errors displayed?

What is your OpenOS version?

Can you install the computer new and run "pastebin run -f icKy25PF" at the start BEFORE you install the server tank program?

**Comment by notchriss** [comment]
When I run tank manually it's the same as if it runs on startup

I'll try fresh install and let you know the results
