### ISSUE TITLE
Have Problems with Update

### ISSUE THREAD

**Issue by kferrano** [Nex4rius/Stargate-Programm#373]
http://prntscr.com/kyw09f

**Comment by Nex4rius** [comment]
Try it again now (on a new hdd). This might have fixed it https://github.com/Nex4rius/Nex4rius-Programme/commit/bde1fcf19e746acd4a5d01b2aafff667350e618a
Btw I have only tested it on 1.7.10 so if you are using any other version then it's certain that I can't help.
