### ISSUE TITLE
server only works with wireless network card

### ISSUE THREAD

**Issue by hpf3** [Nex4rius/Stargate-Programm#424]
https://github.com/Nex4rius/Nex4rius-Programme/blob/2113e4824882c449b0d07c648751079f6d0b72b4/Tank/server/tank/anzeige.lua#L98

**Comment by hpf3** [comment]
it would be usefull to make it so the server works with lan only cards that way its easy to setup different displays next to eachother, for example in my case im wanting to put power on one display, fluid on another, and essentia on another.

**Comment by Nex4rius** [comment]
Thanks for the report. It's fixed and it works now again with lan only cards.
