### ISSUE TITLE
The colors on the Computronics lamps are not accurate 

### ISSUE THREAD

**Issue by TofuHell** [Nex4rius/Stargate-Programm#451]
The Computronics colorful lamp colors are not accurate to the stargate menu.
1. Red appears when the Iris closes. Yellow is supposed to appear.
2. Yellow appears when dialing another stargate. it is supposed to appear when the iris is closed.
3. Yellow still appears when the Stargate is fully connected.
There may be more issues with the colors but I have not encountered it

**Comment by Nex4rius** [comment]
They were never supposed to be the same as for the colors of the redstone output.

It's like this:
red:
- iris closed
- other side reported that the iris is closed (outgoing wormhole)

green:
- a correct IDC was received (incoming wormhole)
- the other side reported that the iris is open (outgoing wormhole)

yellow:
- dialling out
- connected and no response from the other side (outgoing wormhole)

orange:
- dialling in
- connected and no response from the other side (incoming wormhole)

white:
- stargate is idle

black:
- nexDHD was turned off
