### ISSUE TITLE
IDC blocked before I could send it?

### ISSUE THREAD

**Issue by Nyabloody** [Nex4rius/Stargate-Programm#458]
So I was trying the version 3.2.5, the iris issue is gone but I got a new issue.

I get "idc blocked" before I could even send it. Also on the other side it seems something spams "nexDHD" as a IDC and the program catch it up and think it's a IDC while it's not. Probably the reason why I get blocked.

Here is some screenshots of what is happening:

![2020-04-23_20 55 15](https://user-images.githubusercontent.com/4554232/80138544-3eec6800-85a5-11ea-821d-895908874efa.png)
![2020-04-23_20 55 24](https://user-images.githubusercontent.com/4554232/80138552-43188580-85a5-11ea-94f7-8ee89a6b423d.png)

Just a question aside, I see a "side" value defined on "unten" in the configuration, what it does? Redstone output for something?

**Comment by Nex4rius** [comment]
The side value is for direction of the redstone output if the computer has a redstone card.

Thanks for the info. I made some changes with wireless singals when I made this compatible with AUNIS. I have to check that now.

The "nexDHD" signal shouldn't have interfered with the IDC signals. It's for the GDO and for (re-)starting the computer at the other side if it's off.

**Comment by Nex4rius** [comment]
Should be fixed in https://github.com/Nex4rius/Nex4rius-Programme/pull/457
