### ISSUE TITLE
Computer in a loop after update to 3.3.4

### ISSUE THREAD

**Issue by KamaroTheN7** [Nex4rius/Stargate-Programm#468]
Fresh install on blank drive don't help.
![2020-05-05_00 56 58](https://user-images.githubusercontent.com/55023705/81021488-8e674980-8e6b-11ea-9405-c85ae51649e7.png)

**Comment by Nex4rius** [comment]
Thanks for reporting that.

Try 3.3.5

**Comment by KamaroTheN7** [comment]
It works, and that was quick response.
