### ISSUE TITLE
Can you bring back additional screens feature?

### ISSUE THREAD

**Issue by KamaroTheN7** [Nex4rius/Stargate-Programm#473]
That one what is using tier 1 screen don't work at all with AUNIS, that one what use screen tier 3 to display gate state is bugged, it react correctly only when gate is opening or when it is closing.

**Comment by Nex4rius** [comment]
It should technically all work except that SGCraft used numbers and letter for the chevrons and AUNIS uses the "real" chevrons names.

I would have to go through <a href="https://github.com/Nex4rius/Nex4rius-Programme/blob/nexDHD/nexDHD/stargate/chevron.lua#L59-L750">ALL chevrons</a> and assign them the correct name and to be honest right now I don't have the time to do that.

**Comment by Nex4rius** [comment]
done :)

**Comment by KamaroTheN7** [comment]
Nice, thanks!
